function uiclass()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load uiclass                           

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','global GPU p1 p2 iter iterTol EPS wrap1 wrap2;X=[];Y=[];ker=''linear'';GPU=1;C=Inf;p1=1;p2=0;sep=1;iter=1e3;iterTol=1e-3;EPS=1e-3;wrap1=4;wrap2=5;centrefig', ...
	'MenuBar','none', ...
	'Name','Support Vector Classification', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[176 132 800 580], ...
	'Resize','off', ...
	'Tag','Fig1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat14, ...
	'CreateFcn',mat15, ...
	'Position',[0 408.75 76.5 15.75], ...
	'String','GPU', ...
	'Style','checkbox', ...
	'Tag','svmCheckGPU', ...
	'Value',1);

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback',mat2, ...
	'CreateFcn',mat3, ...
	'Position',[40 409.5 80 15], ...
	'String',mat4, ...
	'Style','popupmenu', ...
	'Tag','svmMenu', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat5, ...
	'Position',[514.5 342.75 68.25 23.25], ...
	'String','Load', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat6, ...
	'Position',[514.5 308.25 68.25 23.25], ...
	'String','Save', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat7, ...
	'ForegroundColor',[0 0 1], ...
	'Position',[514.5 261.75 68.25 23.25], ...
	'String','Class A', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat8, ...
	'ForegroundColor',[1 0 0], ...
	'Position',[514.5 225 68.25 23.25], ...
	'String','Class B', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat9, ...
	'Position',[514.5 189 68.25 23.25], ...
	'String','Clear Data', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat10, ...
	'Position',[514.5 115.5 68.25 23.25], ...
	'String','Classify', ...
	'Tag','Pushbutton1');
b = axes('Parent',a, ...
	'Units','points', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[0 0 0], ...
	'ColorOrder',mat11, ...
	'Position',[0 27 496 372], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XLimMode','manual', ...
	'XTickLabelMode','manual', ...
	'YColor',[0 0 0], ...
	'YLimMode','manual', ...
	'YTickLabelMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498485 -0.0222222 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0166667 0.49697 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.00151515 1.09495 0], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498485 1.01414 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat12, ...
	'CreateFcn',mat13, ...
	'Position',[245.25 408.75 76.5 15.75], ...
	'String','Separable', ...
	'Style','checkbox', ...
	'Tag','svmCheckSep', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','C = str2num(get(findobj(gcf,''Tag'',''svmEditBound''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditBound''),''String'',num2str(C));', ...
	'Position',[315 409.5 32 14.25], ...
	'String','Inf', ...
	'Style','edit', ...
	'Tag','svmEditBound', ...
	'Visible','off');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','EPS = str2num(get(findobj(gcf,''Tag'',''svmEditEPS''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditEPS''),''String'',num2str(EPS));', ...
	'Position',[370 409.5 26.5 14.25], ...
	'String','1e-3', ...
	'Style','edit', ...
	'Tag','svmEditEPS', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[350 411 20 12], ...
	'String','EPS', ...
	'Style','text', ...
	'Tag','svmTextEPS', ...
	'Visible','on');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','iter = str2num(get(findobj(gcf,''Tag'',''svmEditIter''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditIter''),''String'',num2str(iter));', ...
	'Position',[420 409.5 26.5 14.25], ...
	'String','1e3', ...
	'Style','edit', ...
	'Tag','svmEditIter', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[400 411 20 12], ...
	'String','iter', ...
	'Style','text', ...
	'Tag','svmTextIter', ...
	'Visible','on');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','iterTol = str2num(get(findobj(gcf,''Tag'',''svmEditIterTol''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditIterTol''),''String'',num2str(iterTol));', ...
	'Position',[470 409.5 26.5 14.25], ...
	'String','1e-3', ...
	'Style','edit', ...
	'Tag','svmEditIterTol', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[455 411 10 12], ...
	'String','tol', ...
	'Style','text', ...
	'Tag','svmTextIterTol', ...
	'Visible','on');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','wrap1 = str2num(get(findobj(gcf,''Tag'',''svmEditWrap1''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditWrap1''),''String'',num2str(wrap1));', ...
	'Position',[527 409.5 12 14.25], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','svmEditWrap1', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[500 411 25 12], ...
	'String','Wrap1', ...
	'Style','text', ...
	'Tag','svmTextWrap1', ...
	'Visible','on');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','wrap2 = str2num(get(findobj(gcf,''Tag'',''svmEditWrap2''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditWrap2''),''String'',num2str(wrap2));', ...
	'Position',[575 409.5 12 14.25], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','svmEditWrap2', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[547 411 25 12], ...
	'String','Wrap2', ...
	'Style','text', ...
	'Tag','svmTextWrap2', ...
	'Visible','on');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','p1 = str2num(get(findobj(gcf,''Tag'',''svmEditP1''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditP1''),''String'',num2str(p1));', ...
	'Position',[160 409.5 23.25 14.25], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','svmEditP1', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[120 410.25 40 12.75], ...
	'Style','text', ...
	'Tag','svmTextP1');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','p2 = str2num(get(findobj(gcf,''Tag'',''svmEditP2''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditP2''),''String'',num2str(p2));', ...
	'Position',[220 409.5 20 14.25], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','svmEditP2', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[190 410.25 20 12.75], ...
	'Style','text', ...
	'Tag','svmTextP2');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[300 411 10 12], ...
	'String','C', ...
	'Style','text', ...
	'Tag','svmTextBound', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[24 6 428.25 14.25], ...
	'Style','text', ...
	'Tag','svmTextStatus');
